version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - .:/prombound
    ports:
      - "9090:9090"
    command: "--config.file=/prombound/prometheus.yml"
  blackbox:
    privileged: true
    image: prom/blackbox-exporter
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    ports:
      - "9115:9115"
    command: "--config.file=/config/blackbox.yml"
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/config/alertmanager.yml
    ports:
      - "9093:9093"
    command: "--config.file=/config/alertmanager.yml"
