version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - .:/prombound
    ports:
      - "9090:9090"
    command: "--config.file=/prombound/prometheus.yml"
  blackbox:
    privileged: true
    image: prom/blackbox-exporter:master
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    ports:
      - "9115:9115"
    command: "--config.file=/config/blackbox.yml"

