global:
  scrape_interval: 1s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9100']
- job_name: mtail
  static_configs:
  - targets: ['localhost:3903']
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [icmp]
  static_configs:
  - targets:
    - 192.168.1.23
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115  # The blackbox exporter's real hostname:port.


alerting:
    alertmanagers:
        - scheme: http
          static_configs:
              - targets: ['localhost:9093']

rule_files:
    - '/home/kon/consumers/alert.rules.yml'
